// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbwIxKc2MDsQU7YFyevgn991Dq1sejQU',
    appId: '1:893648868591:web:44599cf9e570e7e803f71a',
    messagingSenderId: '893648868591',
    projectId: 'career-app-dev-dh',
    authDomain: 'career-app-dev-dh.firebaseapp.com',
    storageBucket: 'career-app-dev-dh.firebasestorage.app',
    measurementId: 'G-TGXTHRP8BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwQZw4qIOUjSEqs-q3hilM5dppcMf_R3s',
    appId: '1:893648868591:android:ea432eaf8d26a06303f71a',
    messagingSenderId: '893648868591',
    projectId: 'career-app-dev-dh',
    storageBucket: 'career-app-dev-dh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUhakcCMe-hDp9E_J42VHo5HcImKsZq8',
    appId: '1:893648868591:ios:cb8b0cdad551010b03f71a',
    messagingSenderId: '893648868591',
    projectId: 'career-app-dev-dh',
    storageBucket: 'career-app-dev-dh.firebasestorage.app',
    iosBundleId: 'com.yourorg.careerapp.dev',
  );
}
