// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2owI7EF14oDNuZBAcZrvPEk5anQRenH4',
    appId: '1:811981988193:web:712793cbebc7c03c446520',
    messagingSenderId: '811981988193',
    projectId: 'career-app-prod-dh',
    authDomain: 'career-app-prod-dh.firebaseapp.com',
    storageBucket: 'career-app-prod-dh.firebasestorage.app',
    measurementId: 'G-VE3N48S2V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8s7EnYvGE0xYdLwLNbAVdNW6uIhUQFo',
    appId: '1:811981988193:android:44205cda05d19702446520',
    messagingSenderId: '811981988193',
    projectId: 'career-app-prod-dh',
    storageBucket: 'career-app-prod-dh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jYFuof7TRgvlN_z_-Rp28nKB9kcc4F4',
    appId: '1:811981988193:ios:10f29458aaa0fc81446520',
    messagingSenderId: '811981988193',
    projectId: 'career-app-prod-dh',
    storageBucket: 'career-app-prod-dh.firebasestorage.app',
    iosBundleId: 'com.yourorg.careerapp',
  );
}
